### ISSUE TITLE
Usually you can ask as an issue, though each project may has its own policies of how to ask questions.

### ISSUE THREAD

**Issue by eva-sui** [ion-oset/developer-commons#30]
Usually you can ask as an issue, though each project may has its own policies of how to ask questions.

_Originally posted by @WISSAL-MN in https://github.com/ion-oset/developer-commons/discussions/29#discussioncomment-3229662_

**Comment by stratofax** [comment]
This really belongs in Discussions, where it originated. In this repo, we like to reserve issues for specific changes or edits to documents or code that have gone through a review process.
